SCREEN_TITLE = "Dr mario"
ASSETS_FOLDER = './assets'
ASSETS_BAR_BLUE_BLUE = f'{ASSETS_FOLDER}/block_y0_x0.jpg'
ASSETS_BAR_RED_BLUE = f'{ASSETS_FOLDER}/block_y0_x1.jpg'
ASSETS_BAR_YELLOW_BLUE = f'{ASSETS_FOLDER}/block_y0_x2.jpg'
ASSETS_BAR_BLUE_RED = f'{ASSETS_FOLDER}/block_y1_x0.jpg'
ASSETS_BAR_RED_RED = f'{ASSETS_FOLDER}/block_y1_x1.jpg'
ASSETS_BAR_YELLOW_RED = f'{ASSETS_FOLDER}/block_y1_x2.jpg'
ASSETS_BAR_BLUE_YELLOW = f'{ASSETS_FOLDER}/block_y2_x0.jpg'
ASSETS_BAR_RED_YELLOW = f'{ASSETS_FOLDER}/block_y2_x1.jpg'
ASSETS_BAR_YELLOW_YELLOW = f'{ASSETS_FOLDER}/block_y2_x2.jpg'

ASSETS_BALL_BLUE = f'{ASSETS_FOLDER}/single_ball_tetris_smile_blue.png'
ASSETS_BALL_YELLOW = f'{ASSETS_FOLDER}/single_ball_tetris_smile_yellow.png'
ASSETS_BALL_RED = f'{ASSETS_FOLDER}/single_ball_tetris_smile_red.png'

ASSETS_VIRUS_BLUE = f'{ASSETS_FOLDER}/blue1.jpg'
ASSETS_VIRUS_BLUE2 = f'{ASSETS_FOLDER}/blue2.jpg'
ASSETS_VIRUS_RED = f'{ASSETS_FOLDER}/red1.jpg'
ASSETS_VIRUS_RED2 = f'{ASSETS_FOLDER}/red2.jpg'
ASSETS_VIRUS_YELLOW = f'{ASSETS_FOLDER}/yellow1.jpg'
ASSETS_VIRUS_YELLOW2 = f'{ASSETS_FOLDER}/yellow2.jpg'

WIN_X = 800
WIN_Y = 600
GRID_SIZE_H = 10
GRID_SIZE_V = 20
ITEM_SIZE = 20

GRID_PAD_LEFT = (WIN_X - (GRID_SIZE_H * ITEM_SIZE)) // 2
GRID_PAD_BOTTOM = (WIN_Y - (GRID_SIZE_V * ITEM_SIZE)) // 2


DIFFICULTY_EASY = 1
DIFFICULTY_MEDIUM = 2
DIFFICULTY_HARD = 3

GAME_SPEED = 1 // 10
KEY_SPEED = 1.2
DROPDOWN_SPEED = 2
ITEM_BLANK = 0
ITEM_VIRUS_R = 1
ITEM_VIRUS_B = 2
ITEM_VIRUS_Y = 3
ITEM_BLOCK_R = 4
ITEM_BLOCK_B = 5
ITEM_BLOCK_Y = 6

ITEM_BAR_B_B = 7
ITEM_BAR_R_B = 8
ITEM_BAR_Y_B = 9
ITEM_BAR_B_R = 10
ITEM_BAR_R_R = 11
ITEM_BAR_Y_R = 12
ITEM_BAR_B_Y = 13
ITEM_BAR_R_Y = 14
ITEM_BAR_Y_Y = 15


LEVEL_MAX = 50


DIRECTION_NEUTRAL = 1
DIRECTION_LEFT = 2
DIRECTION_RIGHT = 3
DIRECTION_DOWN = 4
ROTATION_NEUTRAL = 1
ROTATION_LEFT = 2
ROTATION_RIGHT = 3

